package com.example.minicalc;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RadioGroup;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity implements RadioGroup.OnCheckedChangeListener {

    /**
     * Text field containing the first number.
     */
    private EditText firstNumber;

    /**
     * Text field containing the second number.
     */
    private EditText secondNumber;

    /**
     * Button used to start the calculation.
     */
    private Button button;

    /**
     * Intent generated by this activity when the calculation is started.
     */
    private Intent intent;

    /**
     * Operation performed betweeen the two numbers.
     */
    private String operation;

    /**
     * Radio group containing the list of possible operations.
     */
    private RadioGroup radioGroup;

    /**
     * Integer stating the request code sent by this activity.
     */
    private static final int REQUEST_CODE = 1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Link between the application and the layout.
        this.firstNumber = (EditText) findViewById(R.id.editTextFirstNumber);
        this.secondNumber = (EditText) findViewById(R.id.editTextSecondNumber);
        this.button = (Button) findViewById(R.id.calculate);
        this.intent = new Intent(this, ResultActivity.class);

        this.button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                // Inputs both numbers on the view
                MainActivity.this.intent.putExtra("firstNumber", MainActivity.this.firstNumber.getText().toString());
                MainActivity.this.intent.putExtra("secondNumber", MainActivity.this.secondNumber.getText().toString());
                MainActivity.this.intent.putExtra("operation", MainActivity.this.operation);
                startActivityForResult(MainActivity.this.intent, REQUEST_CODE);
            }
        });

        this.radioGroup = (RadioGroup) findViewById(R.id.radioGroup);
        this.radioGroup.setOnCheckedChangeListener(this);
    }

    @Override
    public void onCheckedChanged(RadioGroup group, int checkedId) {
        switch (checkedId) {
            case R.id.add:
                this.operation = "+";
                break;
            case R.id.subtract:
                this.operation = "-";
                break;
            case R.id.multiply:
                this.operation = "*";
                break;
            case R.id.divide:
                this.operation = "/";
                break;
        }

        Toast.makeText(MainActivity.this, this.operation, Toast.LENGTH_SHORT).show();;
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (resultCode == RESULT_OK && requestCode == REQUEST_CODE) {
            if (data.hasExtra("result")) {
                Toast.makeText(this, "The result of the previous operation was "
                        + data.getExtras().getString("result"), Toast.LENGTH_LONG).show();
            }
        }
    }

}
